  # Self supervised config file for train.py
max_epochs: 50
batch_size: 4
lr: 0.001
R: 8.0
nx: 256
ny: 256
norm_method: 'image_mean'
supervised: false
data_dir: '/home/kadotab/projects/def-mchiew/kadotab/Datasets/M4raw_chunked/'
test_dir: '/home/kadotab/projects/def-mchiew/kadotab/Datasets/M4raw_chunked'
num_workers: 2
contrasts:
  - 't1'
chans: 64
depth: 4
cascades: 12
dataset: 'm4raw'
project: 'MRI Reconstruction'
k_loss: 'l1'
run_name: 'm4raw'
lambda_scaling: 1
limit_volumes: 1
sampling_method: '1d'
mask_threshold_t2: 0.1
mask_threshold_t1: 0.1
mask_threshold_flair: 0.1
upsample_method: 'bilinear'
