# Supervised config file for train.py
max_epochs: 50
batch_size: 4
lr: 0.001
R: 6.0
nx: 128
ny: 128
supervised: false
data_dir: '/home/brenden/Documents/Coding/data/sim_subset'
test_dir: '/home/brenden/Documents/Coding/data/sim_subset'
num_workers: 2
contrasts:
  - 't1'
chans: 18
depth: 4
cascades: 6
dataset: 'brats'
project: 'MRI Reconstruction'
k_loss: 'l1'
lambda_scaling: 1
limit_volumes: 0.2
sampling_method: '1d'
norm_method: 'image_mean'
upsample_method: 'bilinear'
