# Supervised config file for train.py
max_epochs: 100
batch_size: 6
lr: 0.001
R: 4.0
nx: 128
ny: 128
supervised: false
data_dir: '/home/brenden/Documents/Coding/data/fastmri'
test_dir: '/home/brenden/Documents/Coding/data/fastmri'
num_workers: 2
contrasts:
  - 't1'
chans: 18
depth: 4
cascades: 12
dataset: 'fastmri'
project: 'MRI Reconstruction'
k_loss: 'l1'
lambda_scaling: 1
limit_volumes: 1
mask_threshold_t1: 0.0001
sampling_method: '1d'
norm_method: 'image_mean'
upsample_method: 'bilinear'
save_optimizer: True
