  # Self supervised config file for train.py
max_epochs: 50
batch_size: 2
lr: 0.001
R: 8.0
nx: 256
ny: 256
norm_method: 'image_mean'
supervised: false
data_dir: '/home/brenden/Documents/Coding/data/sim_subset'
test_dir: '/home/brenden/Documents/Coding/data/sim_subset'
num_workers: 2
contrasts:
  - 't2'
chans: 32
depth: 4
cascades: 6
dataset: 'brats'
project: 'MRI Reconstruction'
k_loss: 'l1'
lambda_scaling: 1
limit_volumes: 0.2
sampling_method: '2d'
mask_threshold_t2: 0.11
mask_threshold_t1: 0.11
mask_threshold_flair: 0.11

