training_parameters:
  num_workers: 2
  max_epochs: 200
  batch_size: 4
  lr: 0.004

dataset_parameters:
  R: 6.0
  dataset: brats 
  contrasts:
    - t1

  nx: 256
  ny: 256
  limit_volumes: 0.2

model_parameters:
  data_dir: '/home/brenden/Documents/Coding/data/sim_subset_4_chan'
  test_dir: '/home/brenden/Documents/Coding/data/sim_subset_4_chan'
  chans: 64
  cascades: 12
  depth: 4
  image_scaling_lam_full: 8.0e-5
  image_scaling_full_inv: 1.0e-5
  image_scaling_lam_inv: 1.0e-5
  ssim_scaling_delta: 0
  lambda_scaling: 0.65
  sigmoid_slope2: 200
  sigmoid_slope1: 5
  k_loss: 'l1'
  pass_inverse_data: true
  pass_all_data: true
  learn_sampling: true 
  image_loss: ssim
  all_data_no_grad: true 
  inverse_data_no_grad: true 
  pass_through_size: 10
  sampling_method: 1d
  mask_threshold_t2: 0.11
  mask_threshold_t1: 0.11
  mask_threshold_flair: 0.11
  warmup_training: True
  norm_method: 'image_mean'
  warm_start: True
  norm_loss_by_mask: False
  warmup_adam: False


logging_parameters:
  project: "MRI Reconstruction"
