training_parameters:
  num_workers: 2
  max_epochs: 200
  batch_size: 4
  lr: 0.001

dataset_parameters:
  R: 6.0
  dataset: brats 
  contrasts:
    - t1

  nx: 256
  ny: 256
  limit_volumes: 0.2

model_parameters:
  data_dir: '/home/brenden/Documents/Coding/data/M4Raw_first_repetition/'
  test_dir: '/home/brenden/Documents/Coding/data/M4Raw_Averaged/'
  chans: 10
  cascades: 6
  depth: 4
  image_scaling_lam_full: 1.0e-3
  image_scaling_full_inv: 4.0e-4
  image_scaling_lam_inv: 7.0e-4
  lambda_scaling: 0.65
  sigmoid_slope2: 200
  sigmoid_slope1: 5
  k_loss: 'l1'
  pass_inverse_data: true
  pass_all_data: true
  learn_sampling: true 
  image_loss: l1_grad
  all_data_no_grad: true 
  inverse_data_no_grad: false 
  pass_through_size: 10
  sampling_method: 1d
  norm_method: 'image_mean'
  warm_start: False
  norm_loss_by_mask: False
  warmup_adam: False


logging_parameters:
  project: "MRI Reconstruction"
