# Self supervised multi-contrast file config file for train.py
dataset_params:
  data_dir: '/home/brenden/Documents/Coding/data/sim_subset_1e-2_4chan'
  test_dir: '/home/brenden/Documents/Coding/data/sim_subset_1e-2_4chan'
  dataset: 'brats'
  nx: 256
  ny: 256
  num_workers: 2
  norm_method: 'image_mean'
  contrasts:
    - 't1'
    - 't2'
    - 'flair'
    - 't1ce'
  limit_volumes: 0.2
  R: 8.0
  sampling_method: '1d'
  mask_threshold_t1: 0.1

training_params:
  max_epochs: 50
  batch_size: 1
  lr: 0.001
  supervised: false
  k_loss: 'l1'
  lambda_scaling: 1
  project: 'MRI Reconstruction'

model_parameters:
  depth: 4
  chans: 32
  cascades: 4
