# Supervised config file for train.py

model: 'unet'
max_epochs: 20
line_constrained: true
batch_size: 2
lr: 0.001
R: 6.0
R_hat: 2.0
nx: 256
ny: 256
norm_method: 'k'
supervised: false
data_dir: '/home/brenden/Documents/data/M4Raw_first_repetition'
test_dir: '/home/brenden/Documents/data/M4Raw_Averaged'
num_workers: 2
contrasts:
  - 't1'
chans: 18
depth: 4
cascades: 6
dataset: 'm4raw'
project: 'MRI Reconstruction'
k_loss: 'l1'
image_loss_scaling: 1
lambda_scaling: 1
limit_volumes: 0.1
sampling_method: '1d'
norm_method: 'k'
ssdu_partitioning: true
