# Supervised config file for train.py

model: 'unet'
max_epochs: 50
line_constrained: true
batch_size: 1
lr: 0.001
R: 6.0
R_hat: 2.0
nx: 256
ny: 256
norm_method: 'k'
supervised: true
data_dir: '/home/brenden/Documents/data/M4raw_chunked'
contrasts:
  - 't1'
  - 't2'
  - 'flair'
chans: 18
cascades: 6
dataset: 'm4raw'
run_name: 'test'
project: 'MRI Reconstruction'
pi_sampling: false
ssdu_partioning: false
norm_all_k: true
image_space_loss: ''
k_loss: 'norml1l2'
image_loss_scaling: 1