  # Self supervised config file for train.py

  max_epochs: 1
  batch_size: 1
  lr: 0.001
  R: 8.0
  nx: 256
  ny: 256
  norm_method: 'k'
  supervised: false
  data_dir: '/home/brenden/Documents/data/M4Raw_first_repetition'
  test_dir: '/home/brenden/Documents/data/M4Raw_Averaged'
  num_workers: 2
  contrasts:
    - 't1'
    - 't2'
  chans: 18
  depth: 4
  cascades: 20
  dataset: 'm4raw'
  project: 'MRI Reconstruction'
  k_loss: 'l1'
  lambda_scaling: 1
  limit_volumes: 0.1
  sampling_method: '2d'
  norm_method: 'k'
