training_parameters:
  num_workers: 0
  max_epochs: 50
  batch_size: 16
  lr: 0.001
  checkpoint: null
  config: null

dataset_parameters:
  R: 6.0
  dataset: m4raw
  contrasts:
    - t1
    - t2
    - flair
  nx: 128
  ny: 128
  limit_batches: 1.0
  line_constrained: false
  pi_sampling: false

model_parameters:
  R_hat: 2.0
  learn_R: false
  warm_start: false
  data_dir: "/home/brenden/Documents/data/M4raw_chunked"
  chans: 32
  cascades: 6
  ssim_scaling_full: 0.0
  ssim_scaling_set: 0.0
  ssim_scaling_inverse: 0.0
  lambda_scaling: 1
  sigmoid_slope2: 200
  sigmoid_slope1: 5
  pass_inverse_data: false
  pass_all_data: false
  learn_sampling: false
  supervised: false
  image_loss: ssim
  warmup_training: false

logging_parameters:
  project: "MRI Reconstruction"
  run_name: null
