training_parameters:
  num_workers: 6
  max_epochs: 50
  batch_size: 2
  lr: 0.001
  checkpoint: null
  config: null

dataset_parameters:
  R: 6.0
  dataset: m4raw
  contrasts:
    - t1
    - t2
    - flair
  nx: 256
  ny: 256
  limit_batches: 5
  line_constrained: false
  pi_sampling: false

model_parameters:
  R_hat: 2.0
  learn_R: false
  warm_start: false
  data_dir: "/home/brenden/Documents/data/M4raw_chunked/"
  chans: 18
  cascades: 6
  ssim_scaling_full: 1.0e-6
  ssim_scaling_set: 1.0
  ssim_scaling_inverse: 1.0
  lambda_scaling: 1
  sigmoid_slope2: 200
  sigmoid_slope1: 5
  pass_inverse_data: false
  pass_all_data: true
  learn_sampling: true 
  supervised: false
  image_loss: ssim
  warmup_training: false

logging_parameters:
  project: "MRI Reconstruction"
  run_name: null
