training_parameters:
  num_workers: 3
  max_epochs: 200
  batch_size: 1
  lr: 0.001

dataset_parameters:
  R: 6.0
  dataset: m4raw 
  contrasts:
    - t1
    - t2
    - flair
  nx: 256
  ny: 256
  limit_volumes: 0.05

model_parameters:
  learn_R: true
  data_dir: /home/brenden/Documents/data/M4Raw_first_repetition
  test_dir: /home/brenden/Documents/data/M4Raw_Averaged
  chans: 22
  cascades: 4
  ssim_scaling_full: 1.0e-7
  ssim_scaling_set: 1.0e-7
  ssim_scaling_inverse: 7.0e-8
  lambda_scaling: 0.65
  sigmoid_slope2: 200
  sigmoid_slope1: 5
  k_loss: 'l1'
  pass_inverse_data: true
  pass_all_data: true
  learn_sampling: true
  image_loss: ssim
  all_data_no_grad: true 
  pass_through_size: 10
  sampling_method: 1d

logging_parameters:
  project: "MRI Reconstruction"
  run_name: null
