training_parameters:
  num_workers: 1
  max_epochs: 50
  batch_size: 1
  lr: 0.001

dataset_parameters:
  R: 6.0
  dataset: m4raw 
  contrasts:
    - t1
    - t2
    - flair
  nx: 256
  ny: 256
  limit_volumes: 0.25

model_parameters:
  learn_R: true
  data_dir: /home/brenden/Documents/data/M4Raw_first_repetition
  test_dir: /home/brenden/Documents/data/M4Raw_Averaged
  chans: 32
  cascades: 6
  ssim_scaling_full: 1.0e-06
  ssim_scaling_set: 1.0e-06
  ssim_scaling_inverse: 6.0e-07
  lambda_scaling: 0.65
  sigmoid_slope2: 1000
  sigmoid_slope1: 20 
  k_loss: 'l1'
  pass_inverse_data: true
  pass_all_data: true
  learn_sampling: true
  image_loss: ssim
  all_data_no_grad: false 
  pass_through_size: 20

logging_parameters:
  project: "MRI Reconstruction"
  run_name: null
